[2021-06-13 11:08:05,134::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:120@__get_resolver](PID2210639:MainProcess): DNS Server not explicitly given, providing the systemwide one.
[2021-06-13 11:08:05,140::INFO::/usr/lib/python3.9/site-packages/PyFunceble/cli/__init__.py:1200@tool](PID2210639:MainProcess): ARGS:
Namespace(domain=['github.com'], url=None, file=None, url_file=None, adblock=False, aggressive=False, complements=False, filter=None, idna=False, mining=False, auto_continue=False, cooldown_time=0, http=False, local=False, no_special=False, no_whois=False, reputation=False, rpz=False, shadow_file=False, syntax=False, timeout=0, use_reputation_data=False, user_agent=None, verify_ssl_certificate=False, wildcard=False, dns=None, dns_lookup_over_tcp=False, database=False, database_type=None, days_between_db_retest=None, days_between_db_clean=None, whois_database=False, all=True, execution=False, hierarchical=False, host=False, ip=None, json=False, less=False, no_files=False, no_logs=False, no_unified=False, percentage=False, plain=False, dots=False, quiet=False, share_logs=False, simple=False, split=False, store_whois=False, multiprocess=False, multiprocess_merging_mode=None, processes=None, autosave_minutes=None, travis=False, ci=False, ci_branch='master', travis_branch='master', ci_distribution_branch='master', travis_distribution_branch='master', cmd=None, cmd_before_end=None, commit_autosave_message=None, commit_results_message=None, clean=False, clean_all=False, directory_structure=False, iana=False, production=False, public_suffix=False, generate_files_from_database=False, generate_all_files_from_database=False, debug=False)
[2021-06-13 11:08:05,791::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:258@a_record](PID2210639:MainProcess): Getting A record of 'whois.verisign-grs.com'
[2021-06-13 11:08:05,826::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:261@a_record](PID2210639:MainProcess): Could get A record of 'whois.verisign-grs.com': ['192.34.234.30', '192.30.45.30']
[2021-06-13 11:08:05,828::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:258@a_record](PID2210639:MainProcess): Getting A record of 'whois.verisign-grs.com'
[2021-06-13 11:08:05,860::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:261@a_record](PID2210639:MainProcess): Could get A record of 'whois.verisign-grs.com': ['192.30.45.30', '192.34.234.30']
[2021-06-13 11:08:05,964::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:258@a_record](PID2210639:MainProcess): Getting A record of 'github.com'
[2021-06-13 11:08:05,998::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:261@a_record](PID2210639:MainProcess): Could get A record of 'github.com': ['140.82.121.3']
[2021-06-13 11:08:05,998::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/requests.py:216@send](PID2210639:MainProcess): ParseResult(scheme='http', netloc='github.com:80', path='/', params='', query='', fragment=''), 140.82.121.3, http, {'timeout': 3.0, 'verify': False, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
[2021-06-13 11:08:06,076::INFO::/usr/lib/python3.9/site-packages/PyFunceble/engine/mining.py:289@list_of_mined](PID2210639:MainProcess): Getting the list of previously mined data. (DATASET WONT BE LOGGED)
[2021-06-13 11:08:14,799::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:120@__get_resolver](PID2210930:MainProcess): DNS Server not explicitly given, providing the systemwide one.
[2021-06-13 11:08:14,803::INFO::/usr/lib/python3.9/site-packages/PyFunceble/cli/__init__.py:1200@tool](PID2210930:MainProcess): ARGS:
Namespace(domain=['github.com'], url=None, file=None, url_file=None, adblock=False, aggressive=False, complements=False, filter=None, idna=False, mining=False, auto_continue=False, cooldown_time=0, http=False, local=False, no_special=False, no_whois=False, reputation=False, rpz=False, shadow_file=False, syntax=False, timeout=0, use_reputation_data=False, user_agent=None, verify_ssl_certificate=False, wildcard=False, dns=None, dns_lookup_over_tcp=False, database=False, database_type=None, days_between_db_retest=None, days_between_db_clean=None, whois_database=False, all=True, execution=False, hierarchical=False, host=False, ip=None, json=False, less=False, no_files=False, no_logs=False, no_unified=False, percentage=False, plain=False, dots=False, quiet=False, share_logs=False, simple=False, split=False, store_whois=False, multiprocess=False, multiprocess_merging_mode=None, processes=None, autosave_minutes=None, travis=False, ci=False, ci_branch='master', travis_branch='master', ci_distribution_branch='master', travis_distribution_branch='master', cmd=None, cmd_before_end=None, commit_autosave_message=None, commit_results_message=None, clean=False, clean_all=False, directory_structure=False, iana=False, production=False, public_suffix=False, generate_files_from_database=False, generate_all_files_from_database=False, debug=False)
[2021-06-13 11:08:14,976::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:258@a_record](PID2210930:MainProcess): Getting A record of 'whois.verisign-grs.com'
[2021-06-13 11:08:15,009::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:261@a_record](PID2210930:MainProcess): Could get A record of 'whois.verisign-grs.com': ['192.30.45.30', '192.34.234.30']
[2021-06-13 11:08:15,011::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:258@a_record](PID2210930:MainProcess): Getting A record of 'whois.verisign-grs.com'
[2021-06-13 11:08:15,041::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:261@a_record](PID2210930:MainProcess): Could get A record of 'whois.verisign-grs.com': ['192.34.234.30', '192.30.45.30']
[2021-06-13 11:08:15,122::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:258@a_record](PID2210930:MainProcess): Getting A record of 'github.com'
[2021-06-13 11:08:15,152::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:261@a_record](PID2210930:MainProcess): Could get A record of 'github.com': ['140.82.121.3']
[2021-06-13 11:08:15,153::INFO::/usr/lib/python3.9/site-packages/PyFunceble/lookup/requests.py:216@send](PID2210930:MainProcess): ParseResult(scheme='http', netloc='github.com:80', path='/', params='', query='', fragment=''), 140.82.121.3, http, {'timeout': 3.0, 'verify': False, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
[2021-06-13 11:08:15,230::INFO::/usr/lib/python3.9/site-packages/PyFunceble/engine/mining.py:289@list_of_mined](PID2210930:MainProcess): Getting the list of previously mined data. (DATASET WONT BE LOGGED)
